stages:
  download_data:
    cmd: python src/data_downloader.py
    deps:
      - src/data_downloader.py
    outs:
      - data/raw/test.txt
      - data/raw/train.txt
      - data/raw/val.txt

  split_train_data:
    cmd: python src/data_split.py data/raw/train.txt data/interim/train_features.txt data/interim/train_labels.txt
    deps:
      - src/data_split.py
      - data/raw/train.txt
    outs:
      - data/interim/train_features.txt
      - data/interim/train_labels.txt

  split_test_data:
    cmd: python src/data_split.py data/raw/test.txt data/interim/test_features.txt data/interim/test_labels.txt
    deps:
      - src/data_split.py
      - data/raw/test.txt
    outs:
      - data/interim/test_features.txt
      - data/interim/test_labels.txt

  split_val_data:
    cmd: python src/data_split.py data/raw/val.txt data/interim/val_features.txt data/interim/val_labels.txt
    deps:
      - src/data_split.py
      - data/raw/val.txt
    outs:
      - data/interim/val_features.txt
      - data/interim/val_labels.txt

  tokenize_features:
    cmd: python src/tokenize_features.py data/interim/train_features.txt data/interim/val_features.txt data/interim/test_features.txt
    deps:
      - src/tokenize_features.py
      - data/interim/train_features.txt
      - data/interim/val_features.txt
      - data/interim/test_features.txt
    outs:
      - data/interim/tokenized_train.txt
      - data/interim/tokenized_val.txt
      - data/interim/tokenized_test.txt
      - data/interim/tokenizer.pkl

  encode_labels:
    cmd: python src/encode_labels.py data/interim/train_labels.txt data/interim/val_labels.txt data/interim/test_labels.txt
    deps:
      - src/encode_labels.py
      - data/interim/train_labels.txt
      - data/interim/val_labels.txt
      - data/interim/test_labels.txt
    outs:
      - data/interim/encoded_train_labels.txt
      - data/interim/encoded_val_labels.txt
      - data/interim/encoded_test_labels.txt

  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/interim/tokenized_train.txt
      - data/interim/tokenized_val.txt
      - data/interim/encoded_train_labels.txt
      - data/interim/encoded_val_labels.txt
    params:
      - loss_function
      - optimizer
      - batch_train
      - batch_test
      - categories
      - epoch
      - embedding_dimension
    outs:
      - models/model.keras
    metrics:
      - reports/metrics.json
    plots:
      - reports/loss_plot.svg

  upload_model:
    cmd: gsutil cp models/model.keras gs://remla_group_9_model/models.keras
    deps:
      - models/model.keras

  upload_tokenizer:
    cmd: gsutil cp data/interim/tokenizer.pkl gs://remla_group_9_model/tokenizer.pkl
    deps:
      - data/interim/tokenizer.pkl

  test_model:
    cmd: python src/test_model.py
    deps:
      - src/test_model.py
      - data/interim/test_features.txt
      - data/interim/test_labels.txt
      - models/model.keras
    outs:
      - reports/test_accuracy.txt
      - reports/test_loss.txt
      - reports/classification_report.txt
      - reports/confusion_matrix.txt

  test_long_urls:
    cmd: python tests/test_long_urls.py
    deps:
      - tests/test_long_urls.py
      - models/model.keras
    outs:
      - reports/test_long_urls.json

  test_memory_usage:
    cmd: python tests/test_memory_usage.py
    deps:
      - tests/test_memory_usage.py
      - models/model.keras
    outs:
      - reports/test_memory_usage.json

  test_repeatability:
    cmd: python tests/test_repeatability.py
    deps:
      - tests/test_repeatability.py
      - models/model.keras
    outs:
      - reports/test_repeatability.json

  test_tokenization_latency:
    cmd: python tests/test_tokenization_latency.py
    deps:
      - tests/test_tokenization_latency.py
      - data/interim/tokenized_test.txt
    outs:
      - reports/test_tokenization_latency.json

  test_integration:
    cmd: python tests/test_integration.py
    deps:
      - tests/test_integration.py
      - models/model.keras
    outs:
      - reports/test_integration.json
